### ISSUE TITLE
Buffer name

### ISSUE THREAD

**Issue by OXY2DEV** [CWood-sdf/spaceport.nvim#3]
What's the buffer name for Spaceport?

***Context:*** I need it to disable the statuscolumn(using statuscol.nvim).

I tried spceport, Spaceport and it didn't work.

I tried `:lua print(vim.bo.filetype)` and it doesn't show anything(not even nil).

I checked the code and found a variable `buf` but couldn't find a value for it.

**Comment by OXY2DEV** [comment]
Update: Turns out someone just forgot to add a `filetype`(cause the `type` is "string" and the `length` of that string is 0).

The `filetype` is literally "".

So where is the `filetype` set?


Update 2: Attempted to fix the issue by using`buftype`. Still doesn't work.

**Comment by CWood-sdf** [comment]
I dont have a buffer name set right now, but i can publish a change for that later today. 

I'll probably set the buffer name to "spaceport.spaceport", with the file extension as "spaceport"

**Comment by OXY2DEV** [comment]
Thank you.

I have been spending the last hour trying to fix this issue(on the Statuscol.nvim side of the issue) and couldn't get something that worked without breaking something else.

**Comment by CWood-sdf** [comment]
Ok, I just committed the solution:

The buffer name is just 'spaceport', but the file extension is still 'spaceport'

I also added the `User SpaceportEnter` event that you could also attach an autocmd to instead of detecting the filetype.

All of this is documented in the readme, or by running `:h spaceport` in neovim

**Comment by OXY2DEV** [comment]
Problem fixed 😃.

Filetype is now "spaceport" and both events are emitted properly.


A note for people who might use "statuscol.nvim" and "spaceport.nvim": ft_ignore option won't work on `spaceport`.

You need to use `autocmd` to set the `statuscolumn` to "".

![Screenshot_2024-01-30-08-13-35-148_com termux-edit](https://github.com/CWood-sdf/spaceport.nvim/assets/122956967/79bfca2d-bc2d-43ff-bf5a-6e461cacbd53)


I will be closing the issue now.

**Comment by OXY2DEV** [comment]
Just wanted to add a small update.

It appears that spaceport sets the buffer name after all the plugins(such as windline.nvim or statuscol.nvim or any plugin that does something based on the `filetype` & `buftype`) have checked the `filetype` and `buftype`.

So basically spaceport reports that it's a `nofile` buffer and than changes itself to a `spaceport` buffer.

Howerver, I don't really expect this to be fixed as:
A. Not a major issue since you can use the `spaceportEnter` event to hide the statuscolumn and statusline(doesn't work reliably).
B. It just sounds like a too much work to fix(cause I sure couldn't get it to work).


So in the future if someday you decide to update it remember to fix it.

Also, on a side note, it would be really awesome if you could add `highlights` support instead of just colorOpts(in case you are wondering, it's for animated headers[thanks to winsline.nvim]).

**Comment by CWood-sdf** [comment]
I dont think the first problem can be fixed because im setting all the buffer metadata before setting the buffer as the viewed buffer. 

The second problem should be a pretty easy fix, just by adding a property to colorOpts, i could have the name be set. I'll probably publish a change for that tomorrow

**Comment by OXY2DEV** [comment]
Great 👍.

Also can you give a short explanation on what the `l()` function is doing in `screen/recent.lua`? I am trying to add `nvim_webdevicons` support to it(or at the very list add icons so I don't get something like `~/.config/nvim/lua/plugins/` in front of every file name).

I tried to use the config options but I found out that `~/.config/nvim` disables `~/.config/nvim/lua/plugins`(which I think is the expected behaviour).

**Comment by CWood-sdf** [comment]
The l function just returns the lines to be rendered

if you want to replace \~/.config/nvim/lua/plugins, you can use the replaceDirs config option, but replaceDirs is set up to apply all of the replacements consecutively, so if you have replaceDirs set to something like 
{ {"\~/.config/nvim","D"} } and you also want to replace nvim/lua/plugins with something, just add {"D/lua/plugins","@"} to the replaceDirs array after the .config/nvim entry

Or, alternatively, you can place a \~/.config/nvim/lua/plugins entry before the ~/.config/nvim entry

**Comment by OXY2DEV** [comment]
Totally forgot about that 🤦‍♂️.

Anyway thanks for reminding me.

Guess I will write a wrapper for the recent's part to support highlights(file 🗃️ icon highlights). Startup screen is coming along nicely 😁.

![Screenshot_2024-01-30-21-42-43-632_com termux-edit](https://github.com/CWood-sdf/spaceport.nvim/assets/122956967/f96fe5c5-fcdc-4294-adff-aad9afcd5e9f)

**Comment by CWood-sdf** [comment]
I added the ability to make global highlights using the _name property on colorOpts. These highlights can be overridden globally in your config. All these changes are documented in the README

**Comment by OXY2DEV** [comment]
Finally managed to change the recents section.
![Screenshot_2024-01-31-18-57-35-251_com termux](https://github.com/CWood-sdf/spaceport.nvim/assets/122956967/0f1fa922-3a34-40b3-9f8c-8f5640cb21dd)
